global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: docker
    replica: a

scrape_configs:
  # Prometheus self
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Node exporter - Server
  - job_name: "node"
    static_configs:
      - targets:
          - "<IP_ADDR>:9100"     # Server node-exporter

  # cAdvisor - Containers
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "<IP_ADDR>:8085"     # container metrics

  # Thanos components (for long-term storage + queries)
  - job_name: "thanos"
    static_configs:
      - targets:
          - "thanos-sidecar:10902"
          - "thanos-store:10902"
          - "thanos-query:10902"


